# Generated by Django 5.2.4 on 2025-09-16 10:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('delivery_type', models.CharField(choices=[('paid', 'Платная доставка'), ('free', 'Бесплатно'), ('express', 'Экспресс-доставка')], db_index=True, default='paid', max_length=20, verbose_name='Тип доставки')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные '), ('non-cash', 'Безналичные')], db_index=True, default='online', max_length=20, verbose_name='Тип оплаты')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'Обработка'), ('shipped', 'Отправленный'), ('delivered', 'Доставленный'), ('cancelled', 'Отменено'), ('refunded', 'Возвращено')], db_index=True, default='online', max_length=20, verbose_name='Статус заказа')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Номер заказа')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиет')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='goods.product')),
            ],
        ),
    ]
