# Generated by Django 5.2.4 on 2025-09-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('ordinary', 'Обычная доставка'), ('free', 'Бесплатно'), ('express', 'Экспресс-доставка')], db_index=True, default='ordinary', max_length=20, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('online', 'Онлайн картой'), ('someone', 'Онлайн со случайного чужого счета')], db_index=True, default='online', max_length=50, verbose_name='Тип оплаты'),
        ),
    ]
