# Generated by Django 5.2.4 on 2025-09-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_delivery_type_alter_order_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'Обработка'), ('paid', 'Оплачен'), ('shipped', 'Отправленный'), ('delivered', 'Доставленный'), ('cancelled', 'Отменено'), ('refunded', 'Возвращено')], db_index=True, default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
