# Generated by Django 5.2.4 on 2025-09-15 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basket', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='goods.product'),
        ),
        migrations.AddConstraint(
            model_name='basket',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='unique_user_cart'),
        ),
        migrations.AddConstraint(
            model_name='basket',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('session_key',), name='unique_session_key_cart'),
        ),
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together={('basket', 'product')},
        ),
    ]
