# Generated by Django 5.2.4 on 2025-09-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='price',
        ),
    ]
