# Generated by Django 5.2.4 on 2025-09-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_remove_basketitem_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketitem',
            options={'verbose_name': 'Элемент корзины', 'verbose_name_plural': 'Элементы корзины'},
        ),
    ]
