# Generated by Django 5.2.4 on 2025-09-14 04:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('date_from', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('date_to', models.DateTimeField(blank=True, db_index=True, default=None, verbose_name='Дата оконачания')),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ['date_to'],
            },
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='goods.product', verbose_name='Продукт')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sales.sale', verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Скидка на продукт',
                'verbose_name_plural': 'Скидки на продукты',
                'unique_together': {('product', 'sale')},
            },
        ),
    ]
