# Generated by Django 5.2.4 on 2025-09-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleproduct',
            options={'ordering': ['id'], 'verbose_name': 'Скидка на продукт', 'verbose_name_plural': 'Скидки на продукты'},
        ),
    ]
