# Generated by Django 5.2.4 on 2025-09-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
