# Generated by Django 5.2.4 on 2025-09-19 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_alter_order_delivery_type_alter_order_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(default='online', max_length=50, verbose_name='Тип оплаты')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер транзакции')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Заказ')),
            ],
        ),
    ]
