# Generated by Django 5.2.4 on 2025-09-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='total_cost',
        ),
    ]
