# Generated by Django 5.2.4 on 2025-09-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Номер транзакции'),
        ),
    ]
