# Generated by Django 5.2.4 on 2025-09-15 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characteristics', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications_values', to='goods.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specs', to='characteristics.specification', verbose_name='Характеристика'),
        ),
        migrations.AlterUniqueTogether(
            name='productspecification',
            unique_together={('product', 'specification')},
        ),
    ]
