# Generated by Django 5.2.4 on 2025-09-14 04:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('count', models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество товара')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='Описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('free_delivery', models.BooleanField(db_index=True, default=False, verbose_name='Бесплатная доставка')),
                ('rating', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('available', models.BooleanField(db_index=True, default=True, verbose_name='Доступность')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='characteristics.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='characteristics.tag', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(default='products/default_product_image.jpg', upload_to='products/', verbose_name='Ссылка')),
                ('alt', models.CharField(max_length=128, verbose_name='Альтернативный текст')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'Изображения продукта',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'price'], name='goods_produ_categor_8c9d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['rating', '-date'], name='goods_produ_rating_5c03b8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['free_delivery', 'count'], name='goods_produ_free_de_841566_idx'),
        ),
    ]
