# Generated by Django 5.2.4 on 2025-09-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopping_counter',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Количество покупок товара'),
        ),
    ]
