# Generated by Django 5.2.4 on 2025-09-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_product_shopping_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='limited_edition',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Ограниченый тираж'),
        ),
    ]
